{
 "title": "Docker Host",
 "description": "Docker host metrics",
 "tags": [ "system" ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "node_exporter", "label": "Instance", "query": "node_time_seconds" },
   { "name": "cadvisor", "label": "cadvisor", "query": "machine_cpu_cores" }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{instance=\"$node_exporter\"} - node_boot_time_seconds{instance=\"$node_exporter\"}"
    }
   ]
  },
  {
   "title": "CPU Idle",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode=\"idle\", instance=\"$node_exporter\"}[1m])) * 100 / scalar(count(node_cpu_seconds_total{mode=\"user\", instance=\"$node_exporter\"}))"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "machine_cpu_cores{instance=\"$cadvisor\"}"
    }
   ]
  },
  {
   "title": "Available Memory",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes{instance=\"$node_exporter\"}"
    }
   ]
  },
  {
   "title": "Free Swap",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "node_memory_SwapFree_bytes{instance=\"$node_exporter\"}"
    }
   ]
  },
  {
   "title": "Free Boot Storage (Percentage)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100 * (node_filesystem_free_bytes{mountpoint=\"/\", instance=\"$node_exporter\"} / node_filesystem_size_bytes{mountpoint=\"/\", instance=\"$node_exporter\"})"
    }
   ]
  },
  {
   "title": "Load Average 1m",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=\"$node_exporter\"}",
     "legendFormat": "load 1m"
    }
   ]
  },
  {
   "title": "Processes",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_procs_running{instance=\"$node_exporter\"}",
     "legendFormat": "running"
    },
    {
     "expr": "node_procs_blocked{instance=\"$node_exporter\"}",
     "legendFormat": "blocked by I/O"
    }
   ]
  },
  {
   "title": "Interrupts",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": " irate(node_intr_total{instance=\"$node_exporter\"}[5m])",
     "legendFormat": "interrupts"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{instance=\"$node_exporter\"}[1m])) by (mode) * 100 / scalar(count(node_cpu_seconds_total{instance=\"$node_exporter\", mode=\"user\"}))",
     "legendFormat": "{{ mode }}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$node_exporter\"} - (node_memory_MemFree_bytes{instance=\"$node_exporter\"} + node_memory_Buffers_bytes{instance=\"$node_exporter\"} + node_memory_Cached_bytes{instance=\"$node_exporter\"})",
     "legendFormat": "Used"
    },
    { "expr": "node_memory_MemFree_bytes", "legendFormat": "Free" },
    { "expr": "node_memory_Buffers_bytes", "legendFormat": "Buffers" },
    { "expr": "node_memory_Cached_bytes", "legendFormat": "Cached" }
   ]
  },
  {
   "title": "I/O Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_disk_read_bytes_total{instance=\"$node_exporter\"}[1m]))",
     "legendFormat": "read"
    },
    {
     "expr": "sum(irate(node_disk_written_bytes_total{instance=\"$node_exporter\"}[1m]))",
     "legendFormat": "written"
    },
    {
     "expr": "sum(irate(node_disk_io_time_seconds_total{instance=\"$node_exporter\"}[1m]))",
     "legendFormat": "io time"
    }
   ]
  },
  {
   "title": "Network Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{device!=\"lo\", instance=\"$node_exporter\"}[1m])",
     "legendFormat": "In: {{ device }}"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{device!=\"lo\", instance=\"$node_exporter\"}[1m])",
     "legendFormat": "Out: {{ device }}"
    }
   ]
  },
  {
   "title": "Swap Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_SwapTotal_bytes{instance=\"$node_exporter\"} - node_memory_SwapFree_bytes{instance=\"$node_exporter\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_SwapFree_bytes{instance=\"$node_exporter\"}",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Swap I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(node_vmstat_pswpin{instance=\"$node_exporter\"}[1m]) * 4096 or irate(node_vmstat_pswpin{instance=\"$node_exporter\"}[5m]) * 4096",
     "legendFormat": "In"
    },
    {
     "expr": "rate(node_vmstat_pswpout{instance=\"$node_exporter\"}[1m]) * 4096 or irate(node_vmstat_pswpout{instance=\"$node_exporter\"}[5m]) * 4096",
     "legendFormat": "Out"
    }
   ]
  }
 ]
}